services:
  rastapms-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always      
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/rastapms?allowPublicKeyRetrieval=true
      - spring.datasource.username=rastapms
      - spring.datasource.password=rastapms
      - spring.init.mode=always
      - spring.init.schema-locations=optional:classpath*:schema-mysql.sql
    depends_on:
      - mysqldb    

      
  mysqldb:
    image: "mysql:8.0"
    container_name: db
    restart: always    
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: rastapms
      MYSQL_USER: rastapms
      MYSQL_PASSWORD: rastapms
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: