spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rastapms
    username: rastapms
    password: rastapms

  sql:
    init:
      mode: always
      schema-locations: optional:classpath*:schema-mysql.sql

########################################################
################ RASTA PMS PROPERTIES ##################
########################################################
