spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rastapms
    username: rastapms
    password: rastapms

########################################################
################ RASTA PMS PROPERTIES ##################
########################################################
