server:
  servlet:
     context-path: /rastapms
    
    
spring:
  application:
    name: RastaPMS
  profiles:
    active: dev
  messages:
    basename: i18n/common, i18n/rastapms
    encoding: UTF-8
    use-code-as-default-message: true
  mvc:
    format:
      time: HH:mm

########################################################
################ RASTA PMS PROPERTIES ##################
########################################################
rastapms:
  influxdbURL: http://4.232.74.35/api/v2/query
  orgID: fbf2d6df51c7f934
  authorizationtoken: QBmhrJfmainhMOuh3T4S7i5UavyIGQif8xgRkFqScXnuuxZPep7NAwBg1_rQAGrTslOeYx4bJFkpHQ5uK-Bbbg==
  bucket: RASTA
  host: rasta
  medescription: http://localhost:9090/rastame/api/metadataenricher/description
  mecategories: http://localhost:9090/rastame/api/metadataenricher/categories


